// <auto-generated />
namespace cryWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201311110523186_initDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
