// <auto-generated />
namespace cryWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dbupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201311151353264_dbupdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
